baseURL = 'https://scastellotec.github.io/Hugo-001/'
languageCode = 'en-us'
title = 'Mi sitio nuevo'
theme = 'tale'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "Sergio"
    title = "About"
    url = "/about/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0 
