# This is a basic workflow to help you get started with Actions

name: Deploy Hugo Site

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        # install / setup hugo https://github.com/peaceiris/actions-hugo
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
      - run: hugo
        # deploy to destination repo https://github.com/peaceiris/actions-gh-pages
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.SECRET }}
          publish_dir: ./public
