name: Deploy Hugo Site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    # build agent
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      # install / setup hugo
      # https://github.com/peaceiris/actions-hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'

        # build site
      - name: Build
        run: hugo   #--minify

      # deploy to destination repo
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.SECRET }}
          publish_dir: ./public